### ISSUE TITLE
States returned by GET /docs/:id 

### ISSUE THREAD

**Issue by romainbessugesmeusy** [campsi/campsi#4]
`http://api.madewithcampsi.com/docs/293823?return_states?working_draft,published`

**Comment by ChristopheBraud** [comment]
http://api.madewithcampsi.com/docs/293823 return only state requested (default in this case)
http://api.madewithcampsi.com/docs/293823?states=working_draft return default state and working_draft in states key
http://api.madewithcampsi.com/docs/293823?states=working_draft&states=published return default state and working_draft+published in states key
http://api.madewithcampsi.com/docs/293823?states= return all states in states key
